dist: trusty
language: clojure

services:
  - docker

stages:
  - test

env:
  global:
    - DOCKER_USERNAME: domaindrivenarchitecture

jobs:
  include:
    - stage: test
      script:
        - lein test
        - lein uberjar
        - docker build -t dda-smeagol-crate --file integration/docker/image/Dockerfile .
